# https://taskfile.dev

version: '3'

tasks:

  test:
    cmds:
      - go test -v --cover

  build:
    cmds:
      - go build -ldflags "-X main.Version=`git describe --tags`"  -v nept.go
    sources:
      - "nept.go"
    generates:
      - "./nept"

  release:
    interactive: true
    cmds:
      - git tag | tail -5
      - read -p "Version 1.1.1 " version ; git tag $version
      - git push --tags
      - goreleaser release --clean

  default:
    cmds:
      - task: test
      - task: build

